#!/usr/bin/env Rscript

####################        RTrans        #######################################################
library(methods)

timestamp = gsub(':', '-', format(Sys.time(), "%d %b %Y %X "), fixed = TRUE)
#.libPaths(c("/mnt/raid/illumina/geo/R/x86_64-pc-linux-gnu-library", "/mnt/raid/illumina/geo/R/x86_64-pc-linux-gnu-library/3.5", .libPaths()))
#.libPaths(c("/mnt/raid/illumina/Sergey/R_lib/x86_64-pc-linux-gnu-library", "/mnt/raid/illumina/Sergey/R_lib/3.5", .libPaths()))

install.packages.std <- function(pkg.list, force.re.install=FALSE){
  if(force.re.install){
    install.packages(pkgs = pkg.list, dependencies = TRUE)
    return()
  }
  
  
  pkg.to.install = pkg.list[!(pkg.list %in% rownames(installed.packages()))]
  if(length(pkg.to.install) > 0){
    install.packages(pkg.to.install)
  }
  
  for (pkg in pkg.list) {
    if(force.re.install){
      eval(parse(text = sprintf("install.packages(\"%s\", dep = TRUE)",pkg)))
    } else {
      if (!(pkg %in% rownames(installed.packages())))  eval(parse(text = sprintf("install.packages(\"%s\")",pkg)))
    }
  }
  #for (pkg in pkg.list) eval(parse(text = sprintf("suppressPackageStartupMessages(library(\"%s\"))",pkg)))
}

load.packages.std.bio <- function(pkg.list){
  for (pkg in pkg.list) eval(parse(text = sprintf("suppressPackageStartupMessages(library(\"%s\"))",pkg)))
}


cat('Loading/installing packages...\n')

### installing some libraries
# for(c_lib in c('argparser', 'BiocManager', 'funr', 'pryr', 'parallel', 'magrittr')){
#   if(!eval(parse(text = sprintf("suppressWarnings(suppressPackageStartupMessages(require(%s)))", c_lib)))){
#     install.packages(c_lib)
#     eval(parse(text = sprintf("suppressPackageStartupMessages(library(%s))", c_lib)))
#   }
# }

std.libs = c('argparser', 'BiocManager', 'funr', 'pryr', 'parallel', 'magrittr')

install.packages.std(std.libs)
load.packages.std.bio(std.libs)


### defining srartup argements
p <- arg_parser("RTrans transcriptome analysis pipeline")
p <- add_argument(p, "--par", short = '-p', help="Excel workbook with startup parameters filename", default = 'auto')
p <- add_argument(p, "--out-prefix", short = '-o', help="Prefix of output directories", default = NA)
p <- add_argument(p, "--startup-data-rds-file", short = '-rds', help="<generated by RTrans>", default = NA)
p <- add_argument(p, "--threads", short = '-t', help="Threads count", default = 'auto')
p <- add_argument(p, "--create-command-lines-only", short = '-c', help="whether to create only command lines", flag = TRUE)
p <- add_argument(p, "--rtrans-basedir-path", short = '-b', help="path to directory with 'RTrans methods**.R' script", default = 'auto')
p <- add_argument(p, "--models-ids", short = '-m', help="GLM models identifiers (e.g. 1, 2, 3, ...)", nargs = Inf, default = NA)
p <- add_argument(p, "--run-from-rtrans", short = '-r', help="auxiliary flag", flag = TRUE)
p <- add_argument(p, "--generate-summary-reports-only", short = '-g', help="auxiliary flag", flag = TRUE)
p <- add_argument(p, "--successfull-steps-file", short = '-s', help="file with the list of succeful steps", default = NA)
p <- add_argument(p, "--failed-steps-file", short = '-f', help="file with the list of failed steps", default = NA)
p <- add_argument(p, "--logs-dir", short = '-l', help="detailed logs directory", default = NA)
p <- add_argument(p, "--mem-limit", short = '-mem', help="overall memory limit", default = NA)
p <- add_argument(p, "--reinstall-packages", help="whether to re-install R packages", flag = TRUE)
p <- add_argument(p, "--do-not-generate-summary-reports", short = '-d', help="whether to suppress generating summary reports", flag = TRUE)
p = parse_args(p, argv = commandArgs(trailingOnly = TRUE))

current.dir = getwd()

if(is.na(p$out_prefix))  p$out_prefix = sprintf('[Run %s]', timestamp)
if(!(is.na(p$models_ids))) p$models_ids = as.numeric(as.character(p$models_ids))
if(is.na(p$successfull_steps_file))  p$successfull_steps_file = file.path(current.dir, sprintf('%s  Successful.steps.txt', p$out_prefix))
if(is.na(p$failed_steps_file))  p$failed_steps_file = file.path(current.dir, sprintf('%s  Failed.steps.txt', p$out_prefix))
if(is.na(p$logs_dir))  p$logs_dir = file.path(current.dir, sprintf('%s  Logs', p$out_prefix))
dir.create(p$logs_dir, showWarnings = FALSE)

if(!p$run_from_rtrans){
  if(!is.na(p$successfull_steps_file)){
    if(file.exists(p$successfull_steps_file))   invisible(file.remove(p$successfull_steps_file))
  }
  if(!is.na(p$failed_steps_file)){
    if(file.exists(p$failed_steps_file))   invisible(file.remove(p$failed_steps_file))
  }
}

### verify if the parameters file does exist
if(p$par == 'auto'){
  available.Excel.files = list.files(path = '.', pattern = "*.xlsx", full.names = TRUE)
  if(length(available.Excel.files) == 0)
    stop('Cannot find Excel file with parameters. Please specify it with "-p" argument.')
  if(length(available.Excel.files) > 1)
    stop(sprintf('Too many Excel file with parameters (%s). Please specify the needed one with "-p" argument', toString(available.Excel.files)))
  p$par = available.Excel.files[1]
} else if(!file.exists(p$par))
  stop(sprintf('Parameters file "%s" does not exist. Please check "--par" argument', p$par))

### verifying threads count
if(p$threads != 'auto'){
  if(is.na(as.numeric(as.character(p$threads))))
    stop(sprintf('Threads number should be numeric. Instead, it is specified as "%s"', p$threads))
  p$threads = as.numeric(as.character(p$threads))
  if(p$run_from_rtrans & p$threads > 1)
    stop('run-from-rtrans mode support only 1 executing thread')
}

# if(p$run_from_rtrans & all(is.na(p$models_ids)))
#   stop('run-from-rtrans mode is turned on. Please specify GLM models')

### locating RTrans_base directory and checking if there are placed all needed files
suppl.scripts = c('Any.2.Excel.py', 'Classic.enrichment.results.to.Excel.py', 'Cor.tables.2.Excel.py',
  'DE.results.to.Excel.py', 'DE.results.to.Excel.joint.py', 'Excel_formats.py',
  'GO.expression.to.Excel.py', 'GO.GSEA.results.to.Excel.py',
  'Integrate.KEGG.pathway.summaries.py', 'KEGG.DE.summary.to.Excel.py', 'Trends.enrichment.results.to.Excel.py',
  'Run.CL.multithread.py', 'kegg.clusterProfiler.R')

suppl.files = c('Organisms.info.xlsx', 'KEGG.pathway.names.tsv', 'Gene Ontology terms names and descriptions.tsv')
suppl.files.and.scripts = c(suppl.scripts, suppl.files)

if(p$rtrans_basedir_path == 'auto'){
  possible.paths = c(
    file.path(funr::get_script_path(), 'RTrans_main_scripts'),
    file.path(funr::get_script_path(), '..', 'RTrans_main_scripts'),
    file.path(getwd(), 'RTrans_main_scripts'),
    file.path(getwd(), '..', 'RTrans_main_scripts')
  )
  basedir.path = NULL
  RTrans.methods.file = NULL
  for(possible.basedir.path in possible.paths){
    if(file.exists(possible.basedir.path)){
      possible.RTrans.methods.files = list.files(path = possible.basedir.path, pattern = "RTrans.methods", full.names=TRUE)
      if(length(possible.RTrans.methods.files) == 0)  next
      RTrans.methods.file = sort(possible.RTrans.methods.files, decreasing = TRUE)[1]
      basedir.path = possible.basedir.path
      break
    }
  }
  if(is.null(RTrans.methods.file))
    stop(sprintf('Cannot find RTrans_main_scripts directory containing "RTrans methods***.R" and other needed scripts. Please specify it with "--rtrans-basedir-path" argument'))

  absent.suppl.files.and.scripts = suppl.files.and.scripts[!file.exists(file.path(basedir.path, suppl.files.and.scripts))]
  if(length(absent.suppl.files.and.scripts) > 0)
    stop(sprintf('RTrans_main_scripts directory containing "RTrans methods***.R" is found ("%s"). However, there are absent supplementary scripts and other files needed to launch RTrans: %s',
      basedir.path, toString(absent.suppl.files.and.scripts)))

  p$rtrans_basedir_path = basedir.path

} else {
  basedir.path = p$rtrans_basedir_path
  possible.RTrans.methods.files = list.files(path = basedir.path, pattern = "RTrans.methods", full.names=TRUE)
  if(length(possible.RTrans.methods.files) == 0)
    stop(sprintf('Cannot find "RTrans methods***.R" in the directory "%s". Please verify "--rtrans-basedir-path" argument', p$rtrans_basedir_path))
  RTrans.methods.file = sort(possible.RTrans.methods.files, decreasing = TRUE)[1]

  absent.suppl.files.and.scripts = suppl.files.and.scripts[!file.exists(file.path(basedir.path, suppl.files.and.scripts))]
  if(length(absent.suppl.files.and.scripts) > 0)
    stop(sprintf('RTrans_main_scripts directory "%s" should also contain some supplementary scripts and other files needed to launch RTrans: %s. Please verify "--rtrans-basedir-path" argument',
      basedir.path, toString(absent.suppl.files.and.scripts)))
}

source(RTrans.methods.file)

python.bin = Check.Python.availability()
script.dir = Get.script.path(emit.warning = FALSE)

### pre-loading or installing org.db and other 'big' libraries to avoid stack overflow
Pars = Read.Parameters(p$par, prepare.for.ext.DE.data = FALSE, script.dir = script.dir, base.dir = p$rtrans_basedir_path, show.warnings..on.parameters = FALSE)

if(casefold(Pars$Species) %in% c('human', 'hsa', 'has', 'hsapeins', 'homo sapiens'))   {                                   org.db = 'org.Hs.eg.db'
} else if(casefold(Pars$Species) %in% c('mouse', 'mmu', 'mmusculus', 'mus musculus'))  {                                   org.db = 'org.Mm.eg.db' 
} else if(casefold(Pars$Species) %in% c('fly', 'fruitfly', 'dmel', 'drosophila melanogaster', 'dmelanogaster', 'dme')){    org.db = 'org.Dm.eg.db'
} else if(casefold(Pars$Species) %in% c('rat', 'rno', 'rattus', 'rattus norvegicus'))   {                                  org.db = 'org.Rn.eg.db'
} else {
  if(nchar(Pars$Species) != 3) stop(sprintf('Please provide 3-letter code in "Species" parameter (*xslx file). Now, "%s" is provided', Pars$Species))
  org.db = sprintf('org.%s%s.eg.db', toupper(substr(Pars$Species, 1, 1)), tolower(substr(Pars$Species, 2, 2)))
}

init.packages = c(org.db, 'GO.db', 'ReactomePA')

for(c_lib in init.packages){
  # if(!eval(parse(text = sprintf("suppressWarnings(suppressPackageStartupMessages(require(%s)))", c_lib)))){
  #   BiocManager::install(c_lib)
  #   eval(parse(text = sprintf("suppressPackageStartupMessages(library(%s))", c_lib)))
  # }
  if(!(c_lib %in% rownames(installed.packages()))){
    BiocManager::install(c_lib)
  }
}

for(c_lib in init.packages){
  eval(parse(text = sprintf("suppressPackageStartupMessages(library(%s))", c_lib)))
}

### Beginning the analysis. Preparing. Checking counts data. Preprocessing.
if(!is.na(p$startup_data_rds_file)){
  tryCatch(expr = {
    Pre.load.RTrans.packages(Parameters.xlsx.file.name = p$par, script.dir = script.dir, base.dir = p$rtrans_basedir_path,
      current.dir = current.dir, force.re.install = p$reinstall_packages, emit.message = FALSE)
    Startup.Data <<- readRDS(p$startup_data_rds_file)
    if(all(is.na(p$models_ids)) & p$generate_summary_reports_only){
      msg = sprintf('[summarizing] Pre.load.RTrans.packages(...) successful')
    } else
      msg = sprintf('[model %s - "%s"] Pre.load.RTrans.packages(...) successful', toString(p$models_ids), toString(Startup.Data$Pars$Models.to.Test[p$models_ids]))
    cat(msg); cat('\n')
    if(!is.na(p$successfull_steps_file))   write(msg, p$successfull_steps_file, append = TRUE)
  }, error = function (err){
    if(all(is.na(p$models_ids)) & p$generate_summary_reports_only){
      msg = sprintf('[summarizing] Pre.load.RTrans.packages(...) FAILED with error: %s', err)
    } else
      msg = sprintf('[model %s] Pre.load.RTrans.packages(...) FAILED with error: %s', toString(p$models_ids), err)
    if(!is.na(p$failed_steps_file))   write(msg, p$failed_steps_file, append = TRUE)
    cat(msg); cat('\n')
    stop(err)
  })

} else  Startup.Data = Prepare(Parameters.xlsx.file.name = p$par, write.CPM.tables = !p$run_from_rtrans, script.dir = script.dir,
  base.dir = p$rtrans_basedir_path, current.dir = current.dir, force.re.install = p$reinstall_packages, emit.package.message = FALSE)

all.GLM.models = Startup.Data$Pars$Models.to.Test

if(!p$run_from_rtrans & as.character(p$threads) == '1'){
  p$run_from_rtrans = TRUE
  p$models_ids = 1:length(all.GLM.models)
}

system(sprintf('ALLOW_WGCNA_THREADS=%d', parallel::detectCores()))
system(sprintf('export ALLOW_WGCNA_THREADS=%d', parallel::detectCores()))
# warnings()
if(p$generate_summary_reports_only){
  RTrans..pipeline(GLM.model.IDs = c(), Startup.Data = Startup.Data, Parameters.xlsx.file.name = p$par, script.dir = script.dir,
    base.dir = p$rtrans_basedir_path, current.dir = current.dir,
    write.CPM.tables = FALSE, successful.steps.file = p$successfull_steps_file, failed.steps.file = p$failed_steps_file, do_Summarize = TRUE,
    emit.package.message = FALSE)
  quit()

} else if(p$run_from_rtrans){
  if(any(p$models_ids > length(all.GLM.models)))
    stop(sprintf('Incorrect GLM model identifiers: %s. Total number of models is declared is "%s" file is only %d',
      toString(p$models_ids[p$models_ids > length(all.GLM.models)]), length(all.GLM.models)))
  
  # GLM.models.to.test = all.GLM.models[p$models_ids]

  RTrans..pipeline(GLM.model.IDs = p$models_ids, Startup.Data = Startup.Data, Parameters.xlsx.file.name = p$par, script.dir = script.dir,
    base.dir = p$rtrans_basedir_path, current.dir = current.dir,
    write.CPM.tables = FALSE, successful.steps.file = p$successfull_steps_file, failed.steps.file = p$failed_steps_file, do_Summarize = FALSE,
    emit.package.message = FALSE)

} else {
  if(all(is.na(p$models_ids)))  p$models_ids = 1:length(all.GLM.models)

  used_memory = as.numeric(mem_used())
  expected_consuming_memory = 2*used_memory + 1500*1024*1024

  available_memory = NA
  tryCatch(expr = {
    available_memory <<- as.numeric(system("awk '/MemAvailable/ {print $2}' /proc/meminfo", intern=TRUE))*1024
  }, error = function (err){
    available_memory <<- suppressWarnings(memory.size())
    if(available_memory == Inf){
      available_memory <<- NA
      if(p$threads == 'auto'){
        stop(sprintf('Cannot determine available memory size in order to adjust thread counts. Please specify thread counts manually with -t argument or memory limit with -mem argument. Expected memory usage per one threads is %.0f Gb\n',
          expected_consuming_memory/1024/1024/1024))
      }
      msg = sprintf('Cannot determine available memory size. Expected memory usage per one threads is %.0f Gb\n',
        expected_consuming_memory/1024/1024/1024)
      cat(msg)
      warning(msg)
    }
  })

  if(!is.na(available_memory)){
    if(p$threads == 'auto' && available_memory < expected_consuming_memory){
      msg = sprintf('Warning. The available memory size (%.0f Gb) may be not sufficient to run analysis even in 1 thread. Each thread may consume up to %.0f Gb RAM\n',
        available_memory/1024/1024/1024, expected_consuming_memory/1024/1024/1024)
      cat(msg)
      warning(msg)

    } else if (p$threads != 'auto'){
      if(available_memory < expected_consuming_memory*p$threads){
        msg = sprintf('Warning. The available memory size (%.0f Gb) may be not sufficient to run analysis in %d threads. Each thread may consume up to %.0f Gb RAM. It is recommender to lower the number of threads\n',
          p$threads, available_memory/1024/1024/1024, expected_consuming_memory/1024/1024/1024)
        cat(msg)
        warning(msg)
      }
    }
  }

  if(!is.na(p$mem_limit)){
    if(nchar(gsub('[[:alnum:]]', '', p$mem_limit)) != 0)
      stop('Incorrect argument --mem-limit. Examples: 10G, 800M, 1T')
    digits = as.numeric(gsub('[[:alpha:]]', '', p$mem_limit))
    words = toupper(gsub('[[:digit:]]', '', p$mem_limit))
    if(words == ''){
      multiplier = 1
    } else if(words == 'K'){
      multiplier = 1024
    } else if(words == 'M'){
      multiplier = 1024*1024
    } else if(words == 'G'){
      multiplier = 1024*1024*1024
    } else if(words == 'T'){
      multiplier = 1024*1024*1024*1024
    } else {
      stop('Incorrect argument --mem-limit. Examples: 10G, 800M, 1T')
    }
    p$mem_limit = digits*multiplier
    if(p$mem_limit < expected_consuming_memory){
      msg = sprintf('Warning. The specified memory limit (%.0f Gb) may be not sufficient to run analysis even in 1 thread. Each thread may consume up to %.0f Gb RAM\n',
        p$mem_limit/1024/1024/1024, expected_consuming_memory/1024/1024/1024)
      cat(msg)
      warning(msg)
    }
  } else    p$mem_limit = available_memory

  
  if(p$threads == 'auto'){    
    p$threads = max(1, min(parallel::detectCores(), floor(p$mem_limit/expected_consuming_memory)))
    cat(sprintf('Threads count is picked up as %d. One thread may consume up to %.0f Gb RAM. Total %.0f Gb RAM available\n',
      p$threads, expected_consuming_memory/1024/1024/1024, available_memory/1024/1024/1024))
  }
  
  
  commands_list = vector(mode = 'list')
  for(ID in p$models_ids)
    commands_list[[toString(ID)]] = c('Rscript', '--no-save', '--no-restore', file.path(funr::get_script_path(), 'RTrans.R'), '--par', p$par,
      '--threads', '1', '--rtrans-basedir-path', p$rtrans_basedir_path, '--models-ids', toString(ID), '--run-from-rtrans',
      '--successfull-steps-file', p$successfull_steps_file, '--failed-steps-file', p$failed_steps_file,
      '--startup-data-rds-file', 'Startup.Data.rds', '--out-prefix', p$out_prefix)
  
  writeLines(sapply(commands_list, function(x) paste(sprintf('"%s"', x), collapse = ' ')), 'command_list.txt')

  if(!p$create_command_lines_only){
    CL = sprintf('"%s" "%s" --threads %d --commands %s --log-files %s --err-log-files %s --append-logs no --suppress-logging-to-console if_fails --sep "@@@"',
      python.bin,
      file.path(p$rtrans_basedir_path, 'Run.CL.multithread.py'),
      p$threads,
      paste(sprintf('"%s"', sapply(commands_list, function(x) paste(x, collapse = '@@@'))), collapse = ' '),
      paste(sprintf('"%s"', file.path(p$logs_dir, sprintf('Log - %d - %s.txt', p$models_ids, path_sanitize(all.GLM.models[p$models_ids])))), collapse = ' '),
      paste(sprintf('"%s"', file.path(p$logs_dir, sprintf('Err.log - %d - %s.txt', p$models_ids, path_sanitize(all.GLM.models[p$models_ids])))), collapse = ' '))
    
    code = suppressWarnings(system(CL))
    if(code > 0){
      cat(sprintf('Command stopped with exit code %d:\n%s\n', code, CL))
      cat(sprintf('RTrans analysis failed. See logs in the directory "%s"\n', p$logs_dir))
      quit()
    }
  }

  if(!p$do_not_generate_summary_reports){
    command = c('Rscript', '--no-save', '--no-restore', file.path(funr::get_script_path(), 'RTrans.R'), '--par', p$par,
        '--threads', '1', '--rtrans-basedir-path', p$rtrans_basedir_path, '--run-from-rtrans',
        '--successfull-steps-file', p$successfull_steps_file, '--failed-steps-file', p$failed_steps_file,
        '--startup-data-rds-file', 'Startup.Data.rds', '--out-prefix', p$out_prefix,
        '--generate-summary-reports-only')

    write(paste(sprintf('"%s"', command), collapse = ' '), 'command_list.txt', append = TRUE)

    if(!p$create_command_lines_only){
      cat('Generating summary reports...\n')
      CL = sprintf('"%s" "%s" --threads %d --commands "%s" --log-files "%s" --err-log-files "%s" --append-logs no --suppress-logging-to-console if_fails --sep "@@@"',
        python.bin,
        file.path(p$rtrans_basedir_path, 'Run.CL.multithread.py'),
        p$threads,
        paste(command, collapse = '@@@'),
        file.path(p$logs_dir, sprintf('Log - summary.txt')),
        file.path(p$logs_dir, sprintf('Err.log - summary.txt')))

      code = suppressWarnings(system(CL))
      if(code > 0){
        cat(sprintf('Generating summary reports failed. See logs in the directory %s\n', p$logs_dir))
        quit()
      }
    }
  }
}
